#!/usr/bin/env bash
# Start the process
./4-to_infinity_and_beyond &

# Get the PID of the background process
bg_process_pid=$!

# Wait for a key press in the second terminal
read -p "Press Enter to stop the process..."

# Send a signal to terminate the process
kill -TERM "$bg_process_pid"
