#!/usr/bin/env bash
#displays everything in the /etc/passwd
# Using a while loop to read and display information from /etc/passwd

# Using a while loop to read and display information from /etc/passwd
while IFS=: read -r username _ userid _ _ home_directory _
do
  # Display the required information
  echo "Username: $username"
  echo "User ID: $userid"
  echo "Home Directory: $home_directory"
  echo "--------------------------"
done < /etc/passwd
