#!/usr/bin/env bash
# Initialize a counter
counter=1

# Using a while loop to display numbers and messages based on the loop iteration
while [ $counter -le 20 ]
do
  # Check for specific iterations using case statement
  case $counter in
    4)
      echo "$counter and then bad luck from China"
      ;;
    9)
      echo "$counter and then bad luck from Japan"
      ;;
    17)
      echo "$counter and then bad luck from Italy"
      ;;
    *)
      echo $counter
      ;;
  esac

  ((counter++))
done

