#!/usr/bin/env bash
# Initialize variables
hours=0
minutes=1

# Using a while loop to display time for 12 hours and 59 minutes
while [ $hours -lt 13 ]
do
  while [ $minutes -lt 60 ]
  do
    # Display the time
    printf "%02d:%02d\n" $hours $minutes
    
    # Increment minutes
    ((minutes++))

    # Limit the output to the first 70 lines
    if [ $((hours * 60 + minutes)) -eq 70 ]
    then
      exit
    fi
  done
  
  # Reset minutes and increment hours
  minutes=1
  ((hours++))
done
