#!/usr/bin/env bash
# Configures an Ubuntu server as follows:
#   - localhost resolves to 127.0.0.2
#   - facebook.com resolves to 8.8.8.8

sudo cp /etc/hosts ~/hosts.new
sudo echo "127.0.0.2		localhost" > ~/hosts.new
sudo echo "8.8.8.8		facebook.com" >> ~/hosts.new
sudo cp -f ~/hosts.new /etc/hosts
